<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VMNQCVL" ignored="0" tests="1" failures="1" timestamp="2022-05-23T23:53:10 EET" time="6.84" errors="0">
  <testcase name="login" time="0.809" classname="TestLoginPage">
    <failure type="java.lang.AssertionError" message="expected [Your username is invalid!
ﾃ余 but found [You logged into a secure area!
ﾃ余">
      <![CDATA[java.lang.AssertionError: expected [Your username is invalid!
ﾃ余 but found [You logged into a secure area!
ﾃ余
at TestLoginPage.login(TestLoginPage.java:25)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite>
